name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11' # only 11 works for this project 

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:

          node-version: 18.x


      - name: Install Cordova
        run: npm install -g cordova

      - name: Install yarn
        run: npm install -g yarn

      - name: Install app dependencies
        run: yarn setup

      # - name: Configure the platform
      #   run: yarn clean

      - name: Build Android dev apk
        run: yarn build android paid dev

      - name: Build Android prod aab
        run: yarn build android paid prod

      - name: Sign
        run: |
              sudo chmod 777 ./sign.sh
              ./sign.sh

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: ./*.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./*.aab
